theme: jekyll-theme-minimal
title: Operations Research
description: A site for hosting software and data repositories associated with papers appearing in the journal _Operations Research_
logo: logos/OperationsResearch_Cover.png
